Project-test
AbdusSattar-70/Ruby-Group-Capstone pull request #43
Opened 2023-06-14 16:29 UTC by david30-maker

##In this pull request, I implemented test for all implemented methods. 

- [ ] Add unit tests for all implemented methods.

2023-06-14 19:40 UTC, AbdusSattar-70 reviewed
## INVALID CRR 💀 ☠️ 
Hi @david30-maker , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that has a conflict with the dev branch and didn't pass the linter checks and tests It would be better to resolve the issue on git meaning that your local machine instead of GitHub.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-14 22:07 UTC, david30-maker commented
Thanks @AbdusSattar-70 for reviewing my project, Please I don't like the images you used.

2023-06-15 04:44 UTC, AbdusSattar-70 requested changes
## REQUIRED CHANGES 
Hi @david30-maker , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
![AlmostGIF](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/118761303/29056357-debd-4a44-8061-2e68398f1f21)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 04:44 UTC, AbdusSattar-70 commented on classes/game.rb
> +  # end
It would be best to remove the commented code from your codebase to follow best practices and improve the code readability.

2023-06-15 04:44 UTC, AbdusSattar-70 commented on spec/list_all_game_and_author_spec.rb
> +    end
I tested your code, and unfortunately, The `list all authors` can't pass the test. when I tried to show list of all author it looks like awkward photo below:
![1](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/118761303/2c239fdb-7e28-4cd3-86fd-2bfee5b568ca)
![3](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/118761303/466f5deb-4591-46ee-a71f-837b5c0fbb8c)

2023-06-15 04:44 UTC, AbdusSattar-70 commented on spec/list_all_game_and_author_spec.rb
> +      allow(game_author).to receive(:display_message) { |message| output << message << "\n" }
I tested your code, and unfortunately, The `list all games` can't pass the test. when I tried to show list of all games it looks like awkward photo below:
![2](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/118761303/bb11eda5-611a-4ab2-948e-b8dfeb2cd0dd)
![3](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/118761303/32ea92de-f4e4-4c70-99ef-1373f95566f1)

2023-06-15 05:48 UTC, david30-maker commented
Thanks, @AbdusSattar for reviewing my project, but
 do you in any way temper with the code or try to rearrange it, because the code is work on my machine?

2023-06-15 06:13 UTC, AbdusSattar-70 commented
> Thanks, @Abdussattar for reviewing my project, but do you in any way temper with the code or try to rearrange it, because the code is work on my machine?

I didn't make any changes to your code. Why do you think like this. @david30-maker

2023-06-15 09:52 UTC, krisbobo approved these changes
## Status: Approved 🥇 
Hi @david30-maker 
Your project is complete. There's nothing else to say other than...it's time to merge it :shipit: 
Congratulations!!!

![image](https://github.com/AbdusSattar-70/Ruby-Group-Capstone/assets/87911284/a5d6cd28-654c-46d6-9409-08e05cbc9e5a)

## Highlights
✔️ All tests passing
✔️ Linters passing
✔️ All required changes implemented

2023-06-15 09:54 UTC, merged

2023-06-15 09:59 UTC, david30-maker commented
Thanks, @krisbobo for approving my project.